### PR TITLE
Add systemd service example

### PR DESCRIPTION
**Pull request by stelas**

### CODE REVIEW

**Comment by joneskoo** [comment]
Hi and thanks for the contribution. I’m not sure how useful the systemd unit is if there’s nothing special about it for this project? I guess the capabilities are the only non-obvious thing. I see this assumes a service user which is created externally.

I use ruuvi exporter with Alpine Linux myself and it’s on upstream repository (testing).

I wouldn’t use the systemd unit myself for this reason so I’m not sure if it makes sense to include the systemd unit and I guess would be fair to ask of that then what about other platforms. Is it more about packaging, or should upstream projects have some examples too? I don’t know.

I’m considering rejecting this although I do appreciate the contribution and interest in my little project.

**Comment by stelas** [comment]
Hi,

maybe you could add it as an example to the README?

IMHO upstream projects should provide installation instructions, which distro packagers can follow as a guideline.

Also running daemons as root without need is no good security practice... not everyone is using Alpine only inside containers. :wink:

**Comment by joneskoo** [comment]
> maybe you could add it as an example to the README?

This makes sense, especially listing the required capabilities, ideally with a comment why they’re required.

Are you willing to update your PR to do something like this? If not I’ll keep this open and do it some time.

> Also running daemons as root without need is no good security practice... not everyone is using Alpine only inside containers. :wink:

I fully agree, in fact one of the reasons why I used jtaimisto’s bluewalker originally; it didn’t do `sudo hcidump`. My usecase, however, is a single purpose Raspberry Pi appliance so root or not has little difference. There is no other function for the host.

**Comment by stelas** [comment]
> Are you willing to update your PR to do something like this?

Well, give me some time to write it down.

**Pull request closed without merging**
